### ISSUE TITLE
Thanxs for another great tool

### ISSUE THREAD

**Issue by Mike-Blackwell** [laanp/NMS-Creature-Builder#1]
Peter, many thanxs for taking the time to develop and sharing your Creature - Build spreadsheet. 

I noticed that none of the Worms are in your library of creatures other than Flying snake or am I missing something. Also is this all of the possible companions or is there a repository for others...

**Comment by laanp** [comment]
Hi Mike, 

Thanks for checking it out!
Should just open the correct image, if you kept all the file structure the same.  Ie, it will look under the root of the Creature builder worksheet location\pics, or \templates directory.
Let me know if you are still having trouble, and we can sort it out.
